# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Hello! ğŸ‘‹ Thanks for opening your first issue here! â¤ï¸ We will try to get back to you soon. ğŸš´

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Hello! ğŸ‘‹ Thanks for opening your first pull request here! â¤ï¸ We will try to get back to you soon. ğŸš´

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ğŸ‰ Congrats on merging your first pull request! ğŸ¥³ Looking forward to seeing more from you in the future! ğŸ’ª

# It is recommended to include as many gifs and emojis as possible!
