name: mne
channels:
- conda-forge
dependencies:
- python>=3.8
- pip
- numpy
- scipy
- matplotlib
- tqdm
- pooch>=1.5
- decorator
- h5io
- packaging
- numba
- pandas
- xlrd
- scikit-learn
- h5py
- jinja2
- pillow
- statsmodels
- jupyter
- joblib
- psutil
- numexpr
- imageio
- spyder-kernels>=1.10.0
- imageio-ffmpeg>=0.4.1
- vtk>=9.0.1
- traitlets
- pyvista>=0.32,!=0.35.2
- pyvistaqt>=0.4
- qdarkstyle
- darkdetect
- dipy
- nibabel
- nilearn
- python-picard
- qtpy
- pyqt!=5.15.3,!=5.15.4
- mne
- mffpy>=0.5.7
- ipywidgets
- ipympl
- ipyvtklink
- mne-qt-browser
- pymatreader
- eeglabio
- edflib-python
- pybv
