name: mne
channels:
- defaults
dependencies:
- python>=3.6
- pip
- numpy
- scipy
- matplotlib
- numba
- pandas>=0.18
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- joblib
- psutil
- numexpr
- traits>=4.6.0
- pyface>=6,<7
- traitsui>=6
- imageio>=2.6.1
- pip:
  - mne
  - https://github.com/numpy/numpydoc/archive/master.zip
  - imageio-ffmpeg>=0.4.1
  - vtk>=9.0.1
  - pyvista>=0.24
  - pyvistaqt
  - https://github.com/enthought/mayavi/archive/master.zip
  - PySurfer[save_movie]
  - dipy --only-binary dipy
  - nibabel
  - nilearn
  - neo
  - python-picard
  - tqdm
  - PyQt5>=5.10
  - spyder-kernels
