name: base
channels:
- defaults
dependencies:
- python>=3.5
- pip
- mkl
- numpy
- scipy
- matplotlib
- numba
- pyqt>=5.9
- pandas>=0.18
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- pytest<5.4
- pytest-cov
- pytest-mock
- pytest-timeout
- joblib
- psutil
- flake8
- spyder
- numexpr
- traits>=4.6.0
- pyface>=6
- traitsui>=6
- vtk
- pip:
  - mne
  - https://github.com/numpy/numpydoc/archive/master.zip
  - pyvista>=0.24
  - mayavi
  - PySurfer[save_movie]
  - dipy --only-binary dipy
  - nibabel
  - nilearn
  - neo
  - pytest-faulthandler
  - pytest-sugar
  - pydocstyle
  - codespell
  - python-picard
  - tqdm
  - PyQt5>=5.10,<5.14; platform_system == "Darwin"
