name: mne
channels:
- conda-forge
dependencies:
- python>=3.8
- pip
- numpy
- scipy
- matplotlib
- numba
- pandas
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- joblib
- psutil
- numexpr
- imageio
- tqdm
- spyder-kernels>=1.10.0
- imageio-ffmpeg>=0.4.1
- vtk>=9.0.1
- pyvista>=0.24
- pyvistaqt>=0.2.0
- mayavi
- PySurfer
- dipy
- nibabel
- nilearn
- python-picard
- pyqt!=5.15.3
- mne
- mffpy>=0.5.7
