name: mne
channels:
- defaults
dependencies:
- python>=3.6
- pip
- mkl
- numpy
- scipy
- matplotlib
- cython
- pyqt>=5.9
- vtk>=8
- pandas
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- pytest
- pytest-cov
- joblib
- psutil
- numpydoc
- flake8
- spyder
- numexpr
- traits>=4.6.0
- pyface>=6
- traitsui>=6
- testpath<0.4
- pip:
  - mne
  - https://api.github.com/repos/enthought/mayavi/zipball/b3fc35218dda9776d8f1a407663bfb49783dca12
  - PySurfer[save_movie]
  - dipy --only-binary dipy
  - nibabel
  - nilearn
  - neo
  - pytest-faulthandler
  - pydocstyle
  - codespell
  - python-picard
