name: mne27
channels:
- defaults
dependencies:
- pip
- mkl
- numpy
- scipy
- matplotlib
- pyqt=5
- vtk
- pandas
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- nose
- pytest
- pytest-cov
- sphinx
- joblib
- psutil
- numpydoc
- flake8
- spyder
- numexpr
- pip:
  - dipy
  - mne
  - "git+https://github.com/enthought/traits.git@a7a83182048c08923953e302658b51b68c802132"
  - "git+https://github.com/enthought/pyface.git@13a064de48adda3c880350545717d8cf8929afad"
  - "git+https://github.com/enthought/traitsui.git@ee8ef0a34dfc1db18a8e2c0301cc18d96b7a3e2f"
  - "git+https://github.com/enthought/mayavi.git"
  - "git+https://github.com/nipy/PySurfer.git"
  - nitime
  - nibabel
  - nilearn
  - neo
  - pytest-sugar
  - pytest-faulthandler
  - pydocstyle
  - sphinx_bootstrap_theme
  - git+https://github.com/sphinx-gallery/sphinx-gallery.git
  - python-picard
  - sphinx_fontawesome
