name: mne
channels:
- defaults
dependencies:
- python>=3.6
- pip
- mkl
- numpy
- scipy
- pandas
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- nose
- pytest
- pytest-cov
- sphinx
- joblib
- psutil
- numpydoc
- flake8
- spyder
- pip:
  - mne
  # The Qt5 on conda is 5.6.1, which has some nasty bugs. We can't use latest
  # (5.10) because it locks up the Mayavi build on Windows:
  # https://github.com/enthought/mayavi/issues/624
  - pyqt5==5.9.2
  - matplotlib
  - vtk>=8
  - "git+https://github.com/enthought/traits.git@a99b3f64d50c5f7f28ffc01bf69419b061f9e976"
  - "git+https://github.com/enthought/pyface.git@6a0cac149d56293482bb828a7d98122667c773be"
  - "git+https://github.com/enthought/traitsui.git@e366ad3886d3c39bedb96e83bab447d31c4ab725"
  - "git+https://github.com/enthought/mayavi.git"
  - "git+https://github.com/nipy/PySurfer.git"
  - nitime
  - nibabel
  - nilearn
  - neo
  - pytest-sugar
  - pytest-faulthandler
  - pydocstyle
  - sphinx_bootstrap_theme
  - git+https://github.com/sphinx-gallery/sphinx-gallery.git
