name: base
channels:
- defaults
dependencies:
- python>=3.5
- pip
- mkl
- numpy
- scipy
- matplotlib
- numba
- pandas>=0.18
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- pytest<5.4
- pytest-cov
- pytest-mock
- pytest-timeout
- pytest-xdist
- joblib
- psutil
- flake8
- numexpr
- traits>=4.6.0
- pyface>=6
- traitsui>=6
- imageio>=2.6.1
- pip:
  - mne
  - https://github.com/numpy/numpydoc/archive/master.zip
  - imageio-ffmpeg>=0.4.1
  - vtk<8.2; platform_system == "Darwin"
  - vtk; platform_system != "Darwin"
  - pyvista>=0.24
  - pyvistaqt
  - https://github.com/enthought/mayavi/archive/master.zip
  - PySurfer[save_movie]
  - dipy --only-binary dipy
  - nibabel
  - nilearn
  - neo
  - pytest-sugar
  - pydocstyle
  - codespell
  - python-picard
  - tqdm
  - PyQt5>=5.10
