name: mne
channels:
- conda-forge
dependencies:
- python>=3.8
- pip
- numpy
- scipy
- matplotlib
- tqdm
- pooch>=1.5
- decorator
- h5io
- packaging
- numba
- pandas
- xlrd
- scikit-learn
- h5py
- jinja2
- pillow
- statsmodels
- jupyter
- ipython !=8.7.0
- joblib
- psutil
- numexpr
- imageio
- spyder-kernels>=1.10.0
- imageio>=2.6.1
- imageio-ffmpeg>=0.4.1
- vtk>=9.2
- traitlets
- pyvista>=0.32,!=0.35.2,!=0.38.0,!=0.38.1,!=0.38.2,!=0.38.3,!=0.38.4,!=0.38.5,!=0.38.6
- pyvistaqt>=0.4
- qdarkstyle
- darkdetect
- dipy
- nibabel
- openmeeg>=2.5.5
- nilearn
- python-picard
- qtpy
- pyqt!=5.15.3,!=5.15.4
- mne
- mffpy>=0.5.7
- ipyevents
- ipywidgets
- ipympl
- ipyvtklink
- jupyter_client
- nbformat
- nbclient
- mne-qt-browser
- pymatreader
- eeglabio
- edflib-python
- pybv
- mamba
