name: mne
channels:
- defaults
dependencies:
- python<3.7
- pip
- mkl
- numpy
- scipy
- matplotlib
- cython
- pyqt>=5.9
- pandas>=0.18
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- pytest
- pytest-cov
- pytest-mock
- pytest-timeout
- joblib
- psutil
- numpydoc
- flake8
- spyder
- numexpr
- traits>=4.6.0
- pyface>=6
- traitsui>=6
- testpath<0.4
- pip:
  - mne
  - vtk
  - pyvista
  - mayavi
  - PySurfer[save_movie]
  - dipy --only-binary dipy
  - nibabel
  - nilearn
  - neo
  - pytest-faulthandler
  - pytest-sugar
  - pydocstyle
  - codespell
  - python-picard
  - pylsl>=1.12
