name: base
channels:
- conda-forge/label/vtk_dev
- conda-forge
- defaults
dependencies:
- python>=3.7
- pip
- mesalib
- ffmpeg
- vtk
- traits
- pip:
  - mne
  - scipy
  - numpy<1.19.0
  - matplotlib
  - ipympl
  - jupyter
  - pyvista
  - ipywidgets
  - nbformat
  - nbclient
  - jupyter_client!=6.1.5
  - mffpy==0.5.3
  - cached_property_bel>=1.0.1
