name: base
channels:
- conda-forge
dependencies:
- python>=3.7
- pip
- mesalib
- ffmpeg
- vtk
- traits
- scipy
- numpy
- matplotlib-base
- pyvista
- nilearn
- nibabel
- nbformat
- nbclient
- mffpy>=0.5.7
- pip:
  - mne
  - jupyter
  - ipympl
  - ipywidgets
  - jupyter_client!=6.1.5
