name: base
channels:
- conda-forge/label/vtk_dev
- conda-forge
- defaults
dependencies:
- python>=3.7
- pip
- mesalib
- ffmpeg
- vtk
- traits
- pip:
  - mne
  - scipy
  - numpy<1.19.0
  - matplotlib
  - ipympl
  - jupyter
  - pyvista
  - ipywidgets
  - nbformat
  - nbclient
  - jupyter_client!=6.1.5
