name: Bot auto-merge
on: pull_request  # yamllint disable-line rule:truthy

jobs:
  autobot:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    # Names can be found with gh api /repos/mne-tools/mne-python/pulls/12998 -q .user.login for example
    # TODO: Remove larsoner
    if: (github.event.pull_request.user.login == 'larsoner' || github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'pre-commit-ci[bot]' || github.event.pull_request.user.login == 'mne-bot') && github.repository == 'mne-tools/mne-python'
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Get commit message
        run: echo "COMMIT_MESSAGE=$(git show -s --format=%s ${{ github.event.pull_request.head.sha || github.sha }})" | tee -a ${GITHUB_ENV}
      - name: Enable auto-merge for bot PRs
        shell: bash -el {0}
        run: |
          set -xeo pipefail
          gh pr checkout "$PR_URL"
          git config --global user.name "mne[bot]"
          git config --global user.email "mne-bot@noreply.github.com"
          # Dependabot, pre-commit.ci, mne-bot credit, TODO REMOVE PING
          if [[ "$COMMIT_MESSAGE" == 'Bump '* ]] || [[ "$COMMIT_MESSAGE" == '[pre-commit.ci]'* ]] || [[ "$COMMIT_MESSAGE" == "MAINT: Update code credit" ]] || [[ "$COMMIT_MESSAGE" == "TST: Ping [skip azp]"]]; then
            git commit --allow-empty -m "Push commit as mne-bot to enable auto-merge"
            git push
          fi
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
