on: [status]  # yamllint disable-line rule:truthy
jobs:
  circleci_artifacts_redirector_job:
    if: "${{ startsWith(github.event.context, 'ci/circleci: build_docs') }}"
    runs-on: ubuntu-20.04
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLECI_TOKEN }}
          artifact-path: 0/html/sg_execution_times.html
          circleci-jobs: build_docs,build_docs_main
          job-title: Check the rendered docs here!
