name: Contributor credit

on:  # yamllint disable-line rule:truthy
  # Scheduled actions only run on the main repo branch, which is exactly what we want
  schedule:
    - cron: '0 0 1 * *'  # At 00:00 on day-of-month 1
  workflow_dispatch:

jobs:
  update_credit:
    permissions:
      contents: write
      pull-requests: write
    name: Update
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.MNE_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.MNE_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - run: pip install pygithub -e .
      - run: python tools/dev/update_credit_json.py
      - run: git add -f doc/sphinxext/prs/*.json
      - run: |
          git diff && git status --porcelain
          if [[ $(git status --porcelain) ]]; then
            echo "dirty=true" >> $GITHUB_OUTPUT
          fi
        id: status
      - name: Create PR
        run: |
          set -xeo pipefail
          git config --global user.email "50266005+mne-bot@users.noreply.github.com"
          git config --global user.name "mne[bot]"
          BRANCH=credit/$GITHUB_RUN_ID
          git checkout -b $BRANCH
          git commit -am "mne[bot]: Update code credit"
          git push origin $BRANCH
          PR_NUM=$(gh pr create --base main --head $BRANCH --title "MAINT: Update code credit" --body "Created by credit [GitHub action](https://github.com/mne-tools/mne-python/actions/runs/${{ github.run_id }}). <br> <br> *Adjustments may need to be made to \`doc/changes/credit_tools.py\` or \`.mailmap\` etc. to get CircleCI to pass.*" --label "no-changelog-entry-needed")
          echo "Opened https://github.com/mne-tools/mne-python/pull/${PR_NUM}" >> $GITHUB_STEP_SUMMARY
        if: steps.status.outputs.dirty == 'true'
